baseurl      = "https://hungry-hawking-a38a0f.netlify.app/"
title        = "nickhonen's blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
    dateform        = "Mon, Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "01-02-2006"

  # Subtitle for home
    homeSubtitle = "coming 02-22-2022"
    
    github = "https://github.com/nickhonen"   
    twitter = "https://twitter.com/nickhonen4"
    leetcode = "https://leetcode.com/nickhonen/"
    email = "nickhonen@gmail.com"
    opengraph = true
    shareTwitter = true
    disableReadOtherPosts = false

    enableSharingButtons = true

  # Metadata mostly used in document's head
    description = "personal portfolio and blog of Nicholas Honen"
    headline = "nickhonens blog"
    intro = true
    keywords = "homepage, blog, portfolio, developer, software engineer, self-taught"
    images = [""]

[[params.social]]
  name = "github"
  url = "https://github.com/nickhonen"

[[params.social]]
  name = "twitter"
  url = "https://twitter.com/nickhonen4"

[[params.social]]
  name = "leetcode"
  url = "https://leetcode.com/nickhonen/"

# Fixes bug I think
[taxonomies]
  tag      = "tags"
  category = "categories"

[menu]
[[menu.main]]
  identifier = "progress"
  name       = "Progress"
  url        = "https://docs.google.com/spreadsheets/d/1ft73AihxztEmsxfD29WYLCMsv73oqUOMzKgksdcsKLI/edit?usp=sharing"

# posts is a default taxonomy of hugo, not gonna mess with it for now.
[[menu.main]]
  identifier = "blog"
  name       = "Posts"
  url        = "/posts"
  weight = -110
  [menu.main.params]
    class = 'highlight-menu-item'





