baseurl      = "https://nickhonen.com/"
title        = "Nicholas Honen"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
author       = "Nicholas Honen"

[params]
    dateform        = "Mon, Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "01-02-2006"
    dateformNumTime = "01-02-2006 3:05PM"


  # Subtitle for home
    homeSubtitle = "21 years old, learning how to engineer software"
    github = "https://github.com/nickhonen"   
    twitter = "https://twitter.com/nickhonen4"
    leetcode = "https://leetcode.com/nickhonen/"
    opengraph = true
    shareTwitter = true
    disableReadOtherPosts = false
    mainSections = ["posts"]
    readMore = true
    disbleSummary = false

    enableThemeToggle = true

    enableSharingButtons = false

  # Metadata mostly used in document's head
    description = "Nicholas Honen blog, documenting my progress learning web development"
    headline = "nickhonens blog"
    intro = true
    keywords = "homepage, blog, portfolio, developer, software engineer, self-taught, albany, new york, tutor, full stack"
    images = [""]

  # Commento is more than just a comments widget you can embed — 
  # it’s a return to the roots of the internet. 
  # An internet without the tracking and invasions of privacy. 
  # An internet that is simple and lightweight. 
  # An internet that is focused on interesting discussions, not ads. 
  # A better internet.
  # Uncomment this to enable Commento.
[params.commento]
url = ""

#  [params.portrait]
#     path     = "/img/image.jpg"
#     alt      = "Portrait"
#     maxWidth = "50px"


[[params.social]]
  name = "github"
  url = "https://github.com/nickhonen"

[[params.social]]
  name = "twitter"
  url = "https://twitter.com/nickhonen4"

[[params.social]]
  name = "leetcode"
  url = "https://leetcode.com/nickhonen/"

# Fixes bug I think
[taxonomies]
  tag      = "tags"
  category = "categories"

# About section when I add it, need to make an about.md in the root of content folder
# [[menu.main]]
#   identifier = "about"
#   name = "about"
#   title = "About"
#   url = "/about"

[[menu.main]]
  identifier = "progress"
  name       = "progress"
  url        = "https://docs.google.com/spreadsheets/d/1ft73AihxztEmsxfD29WYLCMsv73oqUOMzKgksdcsKLI/edit?usp=sharing"

[[menu.main]]
  identifier = "blog"
  name       = "posts"
  url        = "/posts"

[params.logo]
    logoMark     = ">"
    logoText     = "$ cd /home/"
    logoHomeLink = "/"

    # Set true to remove the logo cursor entirely.
    # logoCursorDisabled = false
    # Set to a valid CSS color to change the cursor in the logo.
    # logoCursorColor    = "#67a2c9"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    # logoCursorAnimate  = "2s"